on:
  push:
    branches:
      - main 

jobs:
  static_analysis:
    name: Static Analysis

    run_tests_macos:
    name: Run Tests on macOS
    runs-on: macos-latest 
   
    #not necessary in this case, but good practice apparently, so you can change which branch its running on.
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Static Analysis
      run: flake8 shopping_cart.py 
    
    - name: Run Test suite
      run: python -m unittest test_shopping_cart.py
