name: Static Analysis and Tests

on:
  push:
    branches:
      - main 

jobs:
  static_analysis:
    name: Static Analysis
    runs-on: macos-latest 
   
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

    - name: Run Static Analysis
      run: flake8 shopping_cart.py 
    
    - name: Run Test suite
      run: python -m unittest test_shopping_cart.py
